### ISSUE TITLE
Create CEO project unresponsive

### ISSUE THREAD

**Issue by flandsberg** [openforis/accuracy-assessment#12]
Hi,

Nothing happens when clicking on "Create CEO project" on the last page of Sepal.

Thanks,

Florence

**Comment by habibw2** [comment]
Hi,

I am having the same issue. "Create CEO project" as well as "Download as Collect Earth project(.cep)" is unresponsive.

Thanks,
Wahaj

**Comment by lecrabe** [comment]
I manage to use your map and generate the CEO project URL and the CEP file
For instance this one
https://collect.earth/collection?projectId=21017&tokenKey=77bfe95b-faad-46dc-b373-44d9a8f1fe3f

It should give you an interface like this
![image](https://user-images.githubusercontent.com/13508875/110648796-516d9100-81b9-11eb-987a-447a8e664951.png)

Maybe your issue is that you have outdated libraries and you should clean your environment

Can you try running the following in your terminal and restart the application ?
`rm -r -f ~/.R/library/*`

**Comment by habibw2** [comment]
Hi,

Sorry, I should have mentioned that I am using the application on the local machine by running it directly in R. 

Thanks,
Wahaj

**Comment by lecrabe** [comment]
Ah... well then it will not work (most probably) as you need to have several libraries and environmental variables setup, it is now essentially designed to work in SEPAL.

This is one core reason for which we developed SEPAL: to make sure people have all the same, maintained environment, to execute tools.

I strongly encourage you to open an account (it's free and public) and check all tools [in the SEPAL platform](https://sepal.io)
