### ISSUE TITLE
Map Input Selection = blank.

### ISSUE THREAD

**Issue by vanderlist** [openforis/accuracy-assessment#6]
hi,

I've used the aa_design shiny web application some months ago. It worked flawlessy and helped me calculating the number of and selecting samplings. 

I tried to use it back today. I had a little trouble since the readme doesn't refer anymore to running the code with shiny straight from github. Luckily I found the needed R code in the history. 
When the application opens in the browsers everything looks fine. But when selecting a 'Map Input' the popup browse screen remains blank. There is no selecting or browsing possible. 

I tried with Firefox53 and IE11.

I've tried updating R (3.4) and RStudio (1.0143) to the latest version. I also tried after installing Rtools (34) which I can't remember being needed before. 

Furthermore, If you are not supporting this kind of use anymore, would it be possible to get an account for SEPAL. Although I'm not in need of cloud processing (the data is not large).

**Comment by lecrabe** [comment]
Hi,
Thanks for your message and the interest in the tool.

We have removed the bits corresponding to the offline installation as we try to maintain only one version. But I think your message is a good encouragement to put it back. You need Rtools if you are running in Windows.

At the moment, the shinyFiles() package is having issues in R 3.4 in Windows which is why you get it blank. We are working on the issue, trying to find a workaround. R3.3.x should work smoothly

In any case, can you send an email to erik.lindquist@fao.org to obtain your sepal account ?

There will be a webinar on the use of those tools on June 6, you can find more info here :

 http://www.gofcgold.wur.nl/redd/redd_training_webinars2017.php?utm_source=Measuremail&utm_medium=email&utm_campaign=GOFC-GOLD+(EN)

**Comment by vanderlist** [comment]
Hi,

Downgrading to R 3.3.3 seems to be doing the trick! Sorry for the inconvenience. Thanks for the information. I will see if I'll ask a SEPAL account. I will close this issue.
