### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by vanderlist** [openforis/accuracy-assessment#9]
Hi,

I've been a user of the accuracy assessment tool of openForis for a while now. I would like to suggest some new options/features:

- it would be great if there would be an option to introduce more ways of stratifying, for instance, uploading a map where the classes are used as strata and and a polygon file with administrative borders that also can be used as strata. It would be even better if the amount of classes for stratification can be set per level of administration (f.i: 8 sub classes on the whole map and 2 global classes per sublevel of administration).

- another feature would be to have an option to select more 'pure' samples, in the sense that a pixel is only chosen as a sample for a certain class if all bordering pixels have the same class. I tried to simulate this with resampling the input map to a coarser resolution, but still too many edge cases exist.

thank you for all your effort, the tool has been put into good use.
all the best,

s.

**Comment by lecrabe** [comment]
hi s.
thanks for you message and interest in the tool, it is encouraging. can you quickly let know for what type of maps you are using the tool ?
regarding your suggestions:
- while it is feasible, it can become quickly complicated to implement this kind of options with the results of creating sampling that do not necessarily comply with the criteria of good practice for accuracy assessment, so we are reluctant to add such features. What is your rationale for trying to do that ? One way to do it would be to breakdown your map into the different admin zones and then use the tools for the different sub-maps. We can think about it though...
- the easiest way to realize that is to create a morphological erosion of your classes: it will keep only the core of the classes. it is an interesting proposal and quite fun to implement but again, it will result in biasing the sampling towards not purely random stratified -> it will artificially improve the results of an AA because the classes will be purer. could you elaborate on why you want to do that ?
curious and happy to discuss further!
best 
Rémi

**Comment by vanderlist** [comment]
Hello Rémi,

The maps we use is a landcover map based on aerial imagery and vector data. The high resolution aerial imagery is automatically processed with an object oriented classification and later on fused with objects from vector data (buildings, roads, agriculture, ...). The vector data has different levels precision that depends on the object. In short the land cover map has 8 classes that can be divided in 2 classes: impervious or not. The map is produced for the a whole region I'm currently working together with a municipality to se if they can use to extract an imperviousness indicator (=% imperviousness surface) that can be monitored and related to certain policy decisions (in the future). Monitoring means that indicators of several version (through the years) of the land cover map are being compared. Thus an estimate and BI is needed.
The municipality has several smaller boroughs. I found out, through testing with them, that is practically unfeasible for them to reference the amount of samples needed for the 8 classes in every borough. Doing it once for the whole municipality is realistic. However, it would be nice to calculate an indicator on the borough level as well. So I thought that selecting samples in 8 classes on the municipality level could be combined with selecting enough samples in 2 classes in every borough. I wanted to see how much more the amount of samples would then be compared to only selecting on the municipality level. It was just an idea. It's to give them options. What you are suggesting I actually already performed by uploading a map with 50 classes, 25 boroughs x 2 classes and processing them with the tool. It took a lot of clicking to complete the tool workflow. For the record: I found out that 25 boroughs was too much, so I suggested cutting it down to 8 zones. 

I can try the out your comment on the second suggestion to preprocess the uploaded map, putting the 'impure' pixels on no data. But wouldn't this influence the samples selection in itself because the surfaces or proportions of classes are influenced? The main idea is to avoid 'edge' cases that the operators have difficulty with referencing. This will result in discarding these samples, meaning that the amount of samples need to be high enough (to have enough left after referencing). But this also means there is a chance that more samples than actually needed are referenced. Making the classes purer is intended to help the operator making a decision. I do get your point that it can influence the results. But in this case the resolution/scale is so high, and the area is so fragmented that 'edge' cases are so common the operator's job can take too long for it to be practical.
